### ISSUE TITLE
.3dsx issue - Failed to get aminet handle, did you patch svc?

### ISSUE THREAD

**Issue by mistaq** [Kyraminol/3DeMore#1]
The .3dsx version doesn't seem to work still, with the error message being the one in the title: 

* Failed to get aminet handle, did you patch svc?

**Comment by Kyraminol** [comment]
I played around and it works, it's that you have to setup Luma or your CFW of choice to patch svcBackdoor (with Luma hold Select on boot and check the last option)
It can't work on unCFW'd 3DS because am:net is privileged (I guess?) so you need to at least run fasthax before that
